available_series <- function(){

  data.frame(
    series_id = c(
      "SECBREPOEFF",
      "SECBDEPOEFF",
      "SECBLENDEFF",
      "SECBREFEFF",
      "SEKEURPMI",
      "SEKUSDPMI",
      "SEKNOKPMI",
      "SEKGBPPMI",
      "SEKJPYPMI",
      "SEKCHFPMI",
      "SEKDKKPMI",
      "SEKPLNPMI",
      "SEKCNYPMI",
      "SEKCADPMI",
      "SEKAUDPMI",
      "SEGVB2YC",
      "SEGVB5YC",
      "SEGVB7YC",
      "SEGVB10YC",
      "USGVB5Y",
      "USGVB10Y",
      "DEGVB5Y",
      "DEGVB10Y",
      "GBGVB5Y",
      "GBGVB10Y",
      "NOGVB10Y",
      "DKGVB10Y",
      "FIGVB10Y",
      "SEKKIX92",
      "SEKTCW92",
      "SEKSDR"
    ),

    description = c(
      "Riksbankens styrränta",
      "Riksbankens inlåningsränta",
      "Riksbankens utlåningsränta",
      "Riksbankens referensränta",
      "Euro mot svenska kronor",
      "Amerikansk dollar mot svenska kronor",
      "Norsk krona mot svenska kronor",
      "Brittiskt pund mot svenska kronor",
      "Japansk yen mot svenska kronor",
      "Schweizisk franc mot svenska kronor",
      "Dansk krona mot svenska kronor",
      "Polsk zloty mot svenska kronor",
      "Kinesisk yuan mot svenska kronor",
      "Kanadensisk dollar mot svenska kronor",
      "Australisk dollar mot svenska kronor",
      "Svensk statsobligation, 2 år",
      "Svensk statsobligation, 5 år",
      "Svensk statsobligation, 7 år",
      "Svensk statsobligation, 10 år",
      "USA:s 5-åriga statsobligationsränta",
      "USA:s 10-åriga statsobligationsränta",
      "Tysklands 5-åriga statsobligationsränta",
      "Tysklands 10-åriga statsobligationsränta",
      "Storbritanniens 5-åriga statsobligationsränta",
      "Storbritanniens 10-åriga statsobligationsränta",
      "Norges 10-åriga statsobligationsränta",
      "Danmarks 10-åriga statsobligationsränta",
      "Finlands 10-åriga statsobligationsränta",
      "KIX-index för svenska kronan",
      "Historiskt TCW-index för svenska kronan",
      "SEK mot IMF:s särskilda dragningsrätter, SDR"
    )
  )
}
